# Generated by Django 6.0.6 on 2026-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profil/'),
        ),
    ]
