# Generated by Django 6.0.6 on 2026-06-23 20:26

import pataba_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pengguna', '0002_userprofile_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, storage=pataba_core.storages.ProfileStorage(), upload_to='profiles/'),
        ),
    ]
