# Generated by Django 6.0.6 on 2026-06-26 01:49

import pataba_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_pengguna', '0003_alter_userprofile_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, storage=pataba_core.storages.ProfileStorage(), upload_to='foto-profil'),
        ),
    ]
