# Generated by Django 6.0.6 on 2026-06-23 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hp', models.CharField(max_length=20)),
                ('kategori', models.CharField(choices=[('permohonan', 'Permohonan Data'), ('kerusakan', 'Laporan Kerusakan'), ('pendaftaran', 'Pendaftaran Aset Pribadi'), ('info_aset', 'Informasi Aset Daerah')], max_length=50)),
                ('pesan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pesan_kontak',
            },
        ),
        migrations.CreateModel(
            name='PublikasiInstansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('PENGUMUMAN', 'Pengumuman Penting'), ('BERITA', 'Berita BPKAD'), ('KEGIATAN', 'Galeri Kegiatan')], max_length=20)),
                ('isi_konten', models.TextField(blank=True, null=True)),
                ('gambar_utama', models.ImageField(blank=True, null=True, upload_to='publikasi_images/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('diupload_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publikasi_instansi',
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
