# Generated by Django 6.0.6 on 2026-06-26 01:49

import pataba_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_publik', '0002_alter_publikasiinstansi_gambar_utama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publikasiinstansi',
            name='gambar_utama',
            field=models.ImageField(blank=True, null=True, storage=pataba_core.storages.PublikasiStorage(), upload_to='konten-publik'),
        ),
    ]
