# Role
ROLE_OPERATOR = 'OPERATOR_OPD'
ROLE_ADMIN = 'ADMIN_BPKAD'
ROLE_SUPER = 'SUPERADMIN'

# Status Verifikasi
STATUS_PENDING = 'BELUM_DIVERIFIKASI'
STATUS_VALID = 'VALID'
STATUS_REVIEW = 'PERLU_REVIEW'