# Generated by Django 6.0.6 on 2026-06-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOPD',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_opd', models.CharField(max_length=255, unique=True)),
                ('kode_opd', models.CharField(blank=True, max_length=30, null=True)),
                ('kode_lokasi', models.CharField(blank=True, max_length=30, null=True)),
                ('singkatan', models.CharField(blank=True, max_length=20, null=True)),
                ('kategori_opd', models.CharField(blank=True, max_length=11, null=True)),
                ('alamat_kantor', models.CharField(blank=True, max_length=255, null=True)),
                ('kepala_opd', models.CharField(blank=True, max_length=150, null=True)),
                ('email_resmi', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'master_opd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefKecamatan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_kecamatan', models.CharField(max_length=100, unique=True)),
                ('kode_kecamatan', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_kecamatan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefKelurahan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_kelurahan', models.CharField(max_length=100)),
                ('kode_kelurahan', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aset_tanah.refkecamatan')),
            ],
            options={
                'db_table': 'ref_kelurahan',
                'managed': True,
                'unique_together': {('kecamatan', 'nama_kelurahan')},
            },
        ),
        migrations.CreateModel(
            name='AsetTanah',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=50, null=True)),
                ('nibar', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_register', models.CharField(blank=True, max_length=20, null=True)),
                ('status_kepemilikan', models.CharField(blank=True, max_length=50, null=True)),
                ('luas_m2', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cara_perolehan', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_perolehan', models.DateField(blank=True, null=True)),
                ('nilai_aset', models.BigIntegerField(blank=True, default=0, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('kelurahan_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_lokasi', models.TextField(blank=True, null=True)),
                ('status_sertifikasi', models.CharField(choices=[('BERSERTIFIKAT', 'Bersertifikat'), ('BELUM_BERSERTIFIKAT', 'Belum Bersertifikat'), ('LAINNYA', 'Lainnya')], default='BELUM_BERSERTIFIKAT', max_length=25)),
                ('nomor_sertifikat', models.CharField(blank=True, max_length=150, null=True)),
                ('status_hak_sementara', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan_sertifikasi_lainnya', models.CharField(blank=True, max_length=255, null=True)),
                ('kondisi_pemanfaatan', models.CharField(blank=True, max_length=50, null=True)),
                ('spesifikasi_nama_barang', models.CharField(blank=True, max_length=255, null=True)),
                ('spesifikasi_lainnya', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status_penggunaan', models.CharField(blank=True, max_length=100, null=True)),
                ('catatan_revisi', models.TextField(blank=True, null=True)),
                ('status_verifikasi', models.CharField(default='BELUM_DIVERIFIKASI', max_length=50)),
                ('satuan', models.CharField(default='m2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aset_tanah.masteropd')),
                ('kelurahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aset_tanah.refkelurahan')),
            ],
            options={
                'db_table': 'master_aset_tanah',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SertifikatTanah',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_sertifikat', models.CharField(max_length=150)),
                ('nama_pemegang_hak', models.CharField(default='Pemerintah Kota Palu', max_length=255)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('peruntukan', models.CharField(blank=True, max_length=255, null=True)),
                ('status_hak', models.CharField(choices=[('HAK_PAKAI', 'Hak Pakai'), ('HAK_MILIK', 'Hak Milik')], max_length=20)),
                ('luas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tanggal_pembuatan', models.DateField(blank=True, null=True)),
                ('tahun_terbit', models.SmallIntegerField(blank=True, null=True)),
                ('nilai', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pemetaan_bpn', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan', models.CharField(choices=[('ASLI', 'Asli'), ('FOTO_KOPI', 'Foto Kopi')], max_length=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('aset_tanah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sertifikat', to='aset_tanah.asettanah')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sertifikat_opd', to='aset_tanah.masteropd')),
            ],
            options={
                'db_table': 'sertifikat_tanah',
                'managed': True,
            },
        ),
    ]
