# Generated by Django 6.0.6 on 2026-06-26 01:49

import django.db.models.deletion
import pataba_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tanah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAsetTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_foto', models.ImageField(storage=pataba_core.storages.AsetTanahStorage(), upload_to='foto-tanah')),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koleksi_foto', to='aset_tanah.asettanah')),
            ],
            options={
                'db_table': 'foto_aset_tanah',
            },
        ),
    ]
