# Generated by Django 6.0.6 on 2026-06-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tanah', '0002_fotoasettanah'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettanah',
            name='nomor_hak',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sertifikattanah',
            name='nomor_hak',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
