# Generated by Django 6.0.6 on 2026-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tanah', '0003_asettanah_nomor_hak_sertifikattanah_nomor_hak'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettanah',
            name='nama_pemegang_hak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='cara_perolehan',
            field=models.CharField(blank=True, choices=[('HIBAH', 'Hibah'), ('PEMBELIAN', 'Pembelian'), ('PENYERAHAN', 'Penyerahan'), ('GANTI_RUGI', 'Ganti Rugi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='keterangan_sertifikasi_lainnya',
            field=models.CharField(blank=True, choices=[('ASLI_PEMKOT', 'Asli - Pemerintah Kota Palu'), ('FOTOKOPI_PEMKOT', 'Fotokopi - Pemerintah Kota Palu'), ('ASLI_NON_PEMKOT', 'Asli - Pribadi/Provinsi/Kementerian'), ('FOTOKOPI_NON_PEMKOT', 'Fotokopi - Pribadi/Provinsi/Kementerian')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='kondisi_pemanfaatan',
            field=models.CharField(blank=True, choices=[('TIDAK_DIKETAHUI', 'Tidak Diketahui'), ('DIMANFAATKAN', 'Dimanfaatkan'), ('TANAH_KOSONG', 'Tanah Kosong'), ('RUSAK', 'Rusak'), ('SENGKETA', 'Sengketa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='status_hak_sementara',
            field=models.CharField(blank=True, choices=[('HAK_PAKAI', 'Hak Pakai'), ('HAK_MILIK', 'Hak Milik')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='status_kepemilikan',
            field=models.CharField(blank=True, choices=[('BELUM_JELAS', 'Belum Jelas'), ('PEMDA', 'Pemda'), ('MASYARAKAT', 'Masyarakat'), ('PROVINSI', 'Provinsi'), ('PUSAT', 'Pusat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asettanah',
            name='status_verifikasi',
            field=models.CharField(choices=[('BELUM_DIVERIFIKASI', 'Belum Diverifikasi'), ('PERLU_REVIEW', 'Perlu Review'), ('VALID', 'Valid')], default='BELUM_DIVERIFIKASI', max_length=50),
        ),
        migrations.AlterField(
            model_name='sertifikattanah',
            name='keterangan',
            field=models.CharField(choices=[('ASLI', 'Asli'), ('FOTOKOPI', 'Foto Kopi')], max_length=15),
        ),
    ]
