# Generated by Django 6.0.6 on 2026-06-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tanah', '0004_asettanah_nama_pemegang_hak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asettanah',
            name='status_sertifikasi',
            field=models.CharField(choices=[('BERSERTIFIKAT', 'Bersertifikat'), ('BELUM_BERSERTIFIKAT', 'Belum Bersertifikat')], default='BELUM_BERSERTIFIKAT', max_length=25),
        ),
    ]
