# Generated by Django 6.0.6 on 2026-07-02 18:55

import apps.aset_tanah.models
import pataba_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aset_tanah', '0005_alter_asettanah_status_sertifikasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoasettanah',
            name='file_foto',
            field=models.ImageField(storage=pataba_core.storages.AsetTanahStorage(), upload_to=apps.aset_tanah.models.get_upload_path),
        ),
    ]
